image: linux

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
  - npm install
  - npm run build
  artifacts:
    paths:
    - public

unittest:
  stage: test
  script:
    - npm install
    - npm test unit

deploy:
  stage: deploy
  script:
    - az webapp up -n iwayfinder-backend
  only:
    - master